# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Config-Patch
version:      0.03
version_from: lib/Config/Patch.pm
installdirs:  site
requires:
    Log::Log4perl:                 0
    MIME::Base64:                  0
    Pod::Usage:                    0
    Set::IntSpan:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
