--- #YAML:1.0
name:                Config-Patch
version:             0.07
abstract:            Patch configuration files and unpatch them later
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Log::Log4perl:                 0
    MIME::Base64:                  0
    Pod::Usage:                    0
    Set::IntSpan:                  0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Mike Schilli <cpan@perlmeister.com>
